apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - istiod
          - istio-ingressgateway
          - istio-egressgateway
  endpoints:
    - port: http-monitoring
      interval: 15s
      path: /metrics
